packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  '@eslint/js': 10.0.1
  '@tailwindcss/vite': 4.2.1
  '@types/node': 24.10.1
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.4
  babel-plugin-react-compiler: 1.0.0
  daisyui: 5.5.19
  eslint: 10.0.2
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.5.2
  globals: 17.3.0
  i18next: 25.8.13
  i18next-browser-languagedetector: 8.2.1
  jotai: 2.18.0
  prettier: 3.8.1
  prettier-plugin-tailwindcss: 0.7.2
  react: 19.2.4
  react-dom: 19.2.4
  react-i18next: 16.5.4
  tailwindcss: 4.2.1
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  valibot: 1.2.0
  vite: 7.3.1

catalogMode: strict

cleanupUnusedCatalogs: true

dedupeDirectDeps: true

minimumReleaseAge: 1440

savePrefix: ''

strictPeerDependencies: false

useNodeVersion: 24.13.0
